PLAY_CONFIRM = 'playConfirm'
PLAY_CANCEL = 'playCancel'
BACK_GAME = 'Back-Game'
BACK_START = 'Back-Start'
BACK_CUTSCENE = 'Back-Cutscene'
SAVE_GAME = 'saveGame'
MENU_PAUSE = 'Menu-Pause'
MENU_GAMEOVER = 'Menu-GameOver'
MENU_START = 'Menu-Start'
MENU_LOAD = 'Menu-Load'
MENU_QUIT = 'Menu-Quit'
CHARA_ADD = 'Chara_Add'
CHARA_SUB = 'Chara_Sub'

FADE_OUT = 'fadeOut'
FADE_IN = 'fadeIn'
FADE_NO = 'noFade'

REFRESH_HUD = 'refreshHUD'
GOT_ITEM = 'gotItem'
PLAYER_HURT = 'playerHurt'
GRUNT_KILLED = 'gruntKilled'
CHANGE_BOARD_HP = 'changeBoardHp'
BOSS_KILLED = 'bossKilled'

# from txt
CALL_BOARD = 'callGameOver'
CHANGE_NAME = 'changeName'
STATUS_BULLETS = 'statusBullets'
